# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-26 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TextSpeech',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=20000)),
                ('language', models.CharField(max_length=10)),
                ('filename', models.CharField(max_length=10)),
            ],
        ),
    ]
